# foodgram models

# INGREDIENT
INGREDIENT_NAME_FIELD_MAX_LENGTH = 128
MEANSUREMENT_UNIT_MAX_LENGTH = 64

# TAG
TAG_FIELD_MAX_LENGTH = 32

# RECIPE
RECIPE_FIELD_MAX_LENGTH = 256
MIN_VALUE_VALIDATOR_COOKING_TIME = 1
MAX_VALUE_VALIDATOR_COOKING_TIME = 32000
SHORT_URL_MAX_LENGTH = 12
LENGTH_STRING_FOR_SHORT_LINK = 10

# RECIPEINGREDIENT
MIN_VALUE_VALIDATOR_AMOUNT = 1
MAX_VALUE_VALIDATOR_AMOUNT = 32000

# users models
USER_NAME_FIELD_MAX_LENGTH = 150
EMAIL_FIELD_MAX_LENGTH = 254
