# Generated by Django 4.2.13 on 2024-07-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Электронная почта пользователя', max_length=254, unique=True, verbose_name='Электронная почта'),
        ),
    ]
